root = "."
tmp_dir = "./logger/tmp" # 默认在root目录下创建tmp目录[可以修改位置]

[build]
cmd = "go build -o ./cmd/tmp/main.exe ./cmd/main.go"
bin = "./cmd/tmp/main.exe"
full_bin = "./cmd/tmp/main.exe"
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
delay = 1000
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

# 退出时删除tmp目录
[misc]
clean_on_exit = true