# 项目配置信息
app:
  name: "lygf" # 程序名字
  mode: "debug" # 模式（gin.DebugMode、gin.ReleaseMode 或 gin.TestMode）
  port: 8080
  version: "v1.0.0"
  machine_id: 1
  start_time: "2025-01-01"

# 认证相关配置
auth:
  jwt_expire: 24  #过期时间一天

# 日志相关配置
log:
  level: "debug" # 日志级别
  filename: "lygf.log" # 日志文件名
  max_size: 200 # 日志的文件大小
  max_age: 30 # 日志的存储时间
  max_backups: 7 # 日志备份数量

# 数据库相关配置
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mysql123"
  dbname: "lygf"
  max_idle_conns: 50
  max_open_conns: 200

# redis相关配置
redis:
  host: "127.0.0.1"
  port: 6379
  db: 2
  pool_size: 100
  password: 123456 

# qq邮箱相关配置
qq_email:
  host: "smtp.qq.com"
  port: 465
  username: "server-lion@qq.com"
  password: "gdgwjsrtqklmhjhi"
  from_email: "server-lion@qq.com"
